export default {
    login: 'auth/',
    getRoles: 'admin/get-roles',
    createShop: 'admin/create-shop',
    deleteShop: 'admin/delete-shop/',
    getShops: 'admin/get-shops',
    createCategory: (ln) => `admin/${ln}/add-category`,
    getCategories: (ln) => `category/${ln}/get-categories`,
    createProduct: (ln) => `shop/${ln}/add-product`,
    getProducts: (ln) => `shop/${ln}/myProducts`,
    deleteProduct: 'shop/delete-product/',
    updateProduct: (ln) => `shop/${ln}/update-product/`,
    getsingleProduct: (ln) => `shop/${ln}/get-product/`,
    getsingleShop: 'shop/myShop',
    updateShop: 'shop/update-shop',
    getRequests: 'admin/get-update-requests',
    approveRequest: 'admin/update-shop/',
    deleteRequest: 'admin/delete-request/',
    getOrders: (ln) => `shop/${ln}/orders`,
    getMyConversation: (ln) => `shop/${ln}/conversations`,
    getMessages: 'customer/get-messages/',
    sendMessage: 'customer/send-message',
    updateOrder: 'shop/update-order-status/',
    getsingleCategory: (ln) => `admin/${ln}/get-category/`,
    updateCategory: (ln) => `admin/${ln}/update-category/`,
    getShop: 'shops/get-single-shop/',
    adminUpdateShop: 'admin/shop-update',
};
